FROM python:3.9

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt
# COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# COPY ./app /code/app
COPY . /code/app

CMD ["fastapi", "run", "app/main.py", "--port", "8123"]

# If running behind a proxy like Nginx or Traefik add --proxy-headers
# CMD ["fastapi", "run", "app/main.py", "--port", "80", "--proxy-headers"]